# Generated by Django 4.0 on 2022-02-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='access',
            field=models.CharField(choices=[('free', 'бесплатно'), ('paid', 'платно')], default='free', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lessons_purchased',
            field=models.ManyToManyField(blank=True, to='backend.Lesson'),
        ),
    ]
