# Generated by Django 4.0 on 2022-02-16 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessonPacks', to='backend.course')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='lessonPack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='backend.lessonpack'),
        ),
    ]
