# Generated by Django 4.0 on 2022-02-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_lessonpack_lesson_lessonpack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lessons_purchased',
        ),
        migrations.AddField(
            model_name='profile',
            name='purchased_lessonPacks',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='backend.LessonPack'),
        ),
    ]
